/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Comment {
  'id' : bigint,
  'createdAt' : bigint,
  'text' : string,
  'author' : Principal,
  'postId' : bigint,
}
export interface ConversationPreview {
  'user' : Principal,
  'lastMessage' : [] | [Message],
}
export interface Message {
  'id' : bigint,
  'content' : string,
  'sender' : Principal,
  'timestamp' : bigint,
  'receiver' : Principal,
}
export interface Notification {
  'id' : bigint,
  'to' : Principal,
  'notificationType' : NotificationType,
  'from' : Principal,
  'read' : boolean,
  'text' : [] | [string],
  'timestamp' : bigint,
  'postId' : [] | [bigint],
}
export type NotificationType = { 'like' : null } |
  { 'comment' : null } |
  { 'mention' : null } |
  { 'follow' : null };
export interface PostView {
  'id' : bigint,
  'authorUsername' : string,
  'likeCount' : bigint,
  'imageBlobKey' : string,
  'createdAt' : bigint,
  'authorAvatarBlobKey' : string,
  'author' : Principal,
  'caption' : string,
  'commentCount' : bigint,
  'likedByMe' : boolean,
}
export interface Profile {
  'bio' : string,
  'username' : string,
  'avatarBlobKey' : string,
  'owner' : Principal,
  'createdAt' : bigint,
}
export interface ReelView {
  'id' : bigint,
  'audioLabel' : string,
  'authorUsername' : string,
  'likeCount' : bigint,
  'createdAt' : bigint,
  'authorAvatarBlobKey' : string,
  'videoBlobKey' : string,
  'author' : Principal,
  'caption' : string,
  'likedByMe' : boolean,
}
export interface Story {
  'id' : bigint,
  'imageBlobKey' : string,
  'createdAt' : bigint,
  'author' : Principal,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addComment' : ActorMethod<[bigint, string], bigint>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createPost' : ActorMethod<[string, string], bigint>,
  'createReel' : ActorMethod<[string, string, string], bigint>,
  'createStory' : ActorMethod<[string], bigint>,
  'deleteComment' : ActorMethod<[bigint], boolean>,
  'deleteNotification' : ActorMethod<[bigint], boolean>,
  'deletePost' : ActorMethod<[bigint], boolean>,
  'deleteReel' : ActorMethod<[bigint], boolean>,
  'followUser' : ActorMethod<[Principal], undefined>,
  'getActiveStories' : ActorMethod<[], Array<Story>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [Profile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getComments' : ActorMethod<[bigint], Array<Comment>>,
  'getConversations' : ActorMethod<[], Array<ConversationPreview>>,
  'getFeed' : ActorMethod<[bigint], Array<PostView>>,
  'getFollowers' : ActorMethod<[Principal], Array<Principal>>,
  'getFollowing' : ActorMethod<[Principal], Array<Principal>>,
  'getMessagesWithUser' : ActorMethod<[Principal], Array<Message>>,
  'getMyProfile' : ActorMethod<[], [] | [Profile]>,
  'getNotifications' : ActorMethod<[], Array<Notification>>,
  'getPost' : ActorMethod<[bigint], [] | [PostView]>,
  'getProfile' : ActorMethod<[Principal], [] | [Profile]>,
  'getReel' : ActorMethod<[bigint], [] | [ReelView]>,
  'getUserProfile' : ActorMethod<[Principal], [] | [Profile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isFollowing' : ActorMethod<[Principal], boolean>,
  'isLiked' : ActorMethod<[bigint], boolean>,
  'isReelLiked' : ActorMethod<[bigint], boolean>,
  'listPosts' : ActorMethod<[], Array<PostView>>,
  'listProfiles' : ActorMethod<[], Array<Profile>>,
  'listReels' : ActorMethod<[], Array<ReelView>>,
  'markAllNotificationsRead' : ActorMethod<[], undefined>,
  'markNotificationRead' : ActorMethod<[bigint], boolean>,
  'saveCallerUserProfile' : ActorMethod<[string, string, string], undefined>,
  'sendMessage' : ActorMethod<[Principal, string], bigint>,
  'toggleLike' : ActorMethod<[bigint], boolean>,
  'toggleReelLike' : ActorMethod<[bigint], boolean>,
  'unfollowUser' : ActorMethod<[Principal], undefined>,
  'upsertProfile' : ActorMethod<[string, string, string], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];