/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const QuestionSticker = IDL.Record({
  'question' : IDL.Text,
  'answers' : IDL.Vec(
    IDL.Record({ 'answer' : IDL.Text, 'viewer' : IDL.Principal })
  ),
});
export const PollSticker = IDL.Record({
  'question' : IDL.Text,
  'votesA' : IDL.Vec(IDL.Principal),
  'votesB' : IDL.Vec(IDL.Principal),
  'optionA' : IDL.Text,
  'optionB' : IDL.Text,
});
export const StorySticker = IDL.Variant({
  'question' : QuestionSticker,
  'poll' : PollSticker,
});
export const StoryReaction = IDL.Record({
  'emoji' : IDL.Text,
  'viewer' : IDL.Principal,
});
export const StoryView = IDL.Record({
  'id' : IDL.Nat,
  'authorUsername' : IDL.Text,
  'imageBlobKey' : IDL.Text,
  'viewerList' : IDL.Vec(IDL.Principal),
  'createdAt' : IDL.Int,
  'authorAvatarBlobKey' : IDL.Text,
  'videoBlobKey' : IDL.Text,
  'author' : IDL.Principal,
  'sticker' : IDL.Opt(StorySticker),
  'reactions' : IDL.Vec(StoryReaction),
});
export const Profile = IDL.Record({
  'bio' : IDL.Text,
  'username' : IDL.Text,
  'avatarBlobKey' : IDL.Text,
  'owner' : IDL.Principal,
  'createdAt' : IDL.Int,
  'website' : IDL.Text,
  'location' : IDL.Text,
});
export const Comment = IDL.Record({
  'id' : IDL.Nat,
  'createdAt' : IDL.Int,
  'text' : IDL.Text,
  'author' : IDL.Principal,
  'postId' : IDL.Nat,
});
export const Message = IDL.Record({
  'id' : IDL.Nat,
  'content' : IDL.Text,
  'sender' : IDL.Principal,
  'timestamp' : IDL.Int,
  'receiver' : IDL.Principal,
});
export const ConversationPreview = IDL.Record({
  'user' : IDL.Principal,
  'lastMessage' : IDL.Opt(Message),
});
export const PostView = IDL.Record({
  'id' : IDL.Nat,
  'authorUsername' : IDL.Text,
  'likeCount' : IDL.Nat,
  'imageBlobKey' : IDL.Text,
  'createdAt' : IDL.Int,
  'authorAvatarBlobKey' : IDL.Text,
  'author' : IDL.Principal,
  'caption' : IDL.Text,
  'commentCount' : IDL.Nat,
  'likedByMe' : IDL.Bool,
});
export const Highlight = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'owner' : IDL.Principal,
  'createdAt' : IDL.Int,
  'coverBlobKey' : IDL.Text,
  'storyIds' : IDL.Vec(IDL.Nat),
});
export const NotificationType = IDL.Variant({
  'like' : IDL.Null,
  'comment' : IDL.Null,
  'mention' : IDL.Null,
  'follow' : IDL.Null,
});
export const Notification = IDL.Record({
  'id' : IDL.Nat,
  'to' : IDL.Principal,
  'notificationType' : NotificationType,
  'from' : IDL.Principal,
  'read' : IDL.Bool,
  'text' : IDL.Opt(IDL.Text),
  'timestamp' : IDL.Int,
  'postId' : IDL.Opt(IDL.Nat),
});
export const ReelView = IDL.Record({
  'id' : IDL.Nat,
  'audioLabel' : IDL.Text,
  'authorUsername' : IDL.Text,
  'likeCount' : IDL.Nat,
  'createdAt' : IDL.Int,
  'authorAvatarBlobKey' : IDL.Text,
  'videoBlobKey' : IDL.Text,
  'author' : IDL.Principal,
  'caption' : IDL.Text,
  'likedByMe' : IDL.Bool,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addComment' : IDL.Func([IDL.Nat, IDL.Text], [IDL.Nat], []),
  'addStoryToHighlight' : IDL.Func([IDL.Nat, IDL.Nat], [IDL.Bool], []),
  'answerQuestion' : IDL.Func([IDL.Nat, IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createHighlight' : IDL.Func([IDL.Text, IDL.Text], [IDL.Nat], []),
  'createPost' : IDL.Func([IDL.Text, IDL.Text], [IDL.Nat], []),
  'createReel' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [IDL.Nat], []),
  'createStory' : IDL.Func([IDL.Text, IDL.Text], [IDL.Nat], []),
  'deleteComment' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'deleteHighlight' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'deleteNotification' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'deletePost' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'deleteReel' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'followUser' : IDL.Func([IDL.Principal], [], []),
  'getActiveStories' : IDL.Func([], [IDL.Vec(StoryView)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(Profile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getComments' : IDL.Func([IDL.Nat], [IDL.Vec(Comment)], ['query']),
  'getConversations' : IDL.Func([], [IDL.Vec(ConversationPreview)], ['query']),
  'getFeed' : IDL.Func([IDL.Nat], [IDL.Vec(PostView)], ['query']),
  'getFollowers' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(IDL.Principal)],
      ['query'],
    ),
  'getFollowing' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(IDL.Principal)],
      ['query'],
    ),
  'getHighlights' : IDL.Func([IDL.Principal], [IDL.Vec(Highlight)], ['query']),
  'getMessagesWithUser' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(Message)],
      ['query'],
    ),
  'getMyHighlights' : IDL.Func([], [IDL.Vec(Highlight)], ['query']),
  'getMyProfile' : IDL.Func([], [IDL.Opt(Profile)], ['query']),
  'getNotifications' : IDL.Func([], [IDL.Vec(Notification)], ['query']),
  'getPost' : IDL.Func([IDL.Nat], [IDL.Opt(PostView)], ['query']),
  'getProfile' : IDL.Func([IDL.Principal], [IDL.Opt(Profile)], ['query']),
  'getReel' : IDL.Func([IDL.Nat], [IDL.Opt(ReelView)], ['query']),
  'getStoryViewers' : IDL.Func([IDL.Nat], [IDL.Vec(IDL.Principal)], ['query']),
  'getUserProfile' : IDL.Func([IDL.Principal], [IDL.Opt(Profile)], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isFollowing' : IDL.Func([IDL.Principal], [IDL.Bool], ['query']),
  'isLiked' : IDL.Func([IDL.Nat], [IDL.Bool], ['query']),
  'isReelLiked' : IDL.Func([IDL.Nat], [IDL.Bool], ['query']),
  'listPosts' : IDL.Func([], [IDL.Vec(PostView)], ['query']),
  'listProfiles' : IDL.Func([], [IDL.Vec(Profile)], ['query']),
  'listReels' : IDL.Func([], [IDL.Vec(ReelView)], ['query']),
  'markAllNotificationsRead' : IDL.Func([], [], []),
  'markNotificationRead' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'reactToStory' : IDL.Func([IDL.Nat, IDL.Text], [], []),
  'removeStoryFromHighlight' : IDL.Func([IDL.Nat, IDL.Nat], [IDL.Bool], []),
  'saveCallerUserProfile' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [],
      [],
    ),
  'sendMessage' : IDL.Func([IDL.Principal, IDL.Text], [IDL.Nat], []),
  'toggleLike' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'toggleReelLike' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'unfollowUser' : IDL.Func([IDL.Principal], [], []),
  'upsertProfile' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [],
      [],
    ),
  'viewStory' : IDL.Func([IDL.Nat], [], []),
  'votePoll' : IDL.Func([IDL.Nat, IDL.Text], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const QuestionSticker = IDL.Record({
    'question' : IDL.Text,
    'answers' : IDL.Vec(
      IDL.Record({ 'answer' : IDL.Text, 'viewer' : IDL.Principal })
    ),
  });
  const PollSticker = IDL.Record({
    'question' : IDL.Text,
    'votesA' : IDL.Vec(IDL.Principal),
    'votesB' : IDL.Vec(IDL.Principal),
    'optionA' : IDL.Text,
    'optionB' : IDL.Text,
  });
  const StorySticker = IDL.Variant({
    'question' : QuestionSticker,
    'poll' : PollSticker,
  });
  const StoryReaction = IDL.Record({
    'emoji' : IDL.Text,
    'viewer' : IDL.Principal,
  });
  const StoryView = IDL.Record({
    'id' : IDL.Nat,
    'authorUsername' : IDL.Text,
    'imageBlobKey' : IDL.Text,
    'viewerList' : IDL.Vec(IDL.Principal),
    'createdAt' : IDL.Int,
    'authorAvatarBlobKey' : IDL.Text,
    'videoBlobKey' : IDL.Text,
    'author' : IDL.Principal,
    'sticker' : IDL.Opt(StorySticker),
    'reactions' : IDL.Vec(StoryReaction),
  });
  const Profile = IDL.Record({
    'bio' : IDL.Text,
    'username' : IDL.Text,
    'avatarBlobKey' : IDL.Text,
    'owner' : IDL.Principal,
    'createdAt' : IDL.Int,
    'website' : IDL.Text,
    'location' : IDL.Text,
  });
  const Comment = IDL.Record({
    'id' : IDL.Nat,
    'createdAt' : IDL.Int,
    'text' : IDL.Text,
    'author' : IDL.Principal,
    'postId' : IDL.Nat,
  });
  const Message = IDL.Record({
    'id' : IDL.Nat,
    'content' : IDL.Text,
    'sender' : IDL.Principal,
    'timestamp' : IDL.Int,
    'receiver' : IDL.Principal,
  });
  const ConversationPreview = IDL.Record({
    'user' : IDL.Principal,
    'lastMessage' : IDL.Opt(Message),
  });
  const PostView = IDL.Record({
    'id' : IDL.Nat,
    'authorUsername' : IDL.Text,
    'likeCount' : IDL.Nat,
    'imageBlobKey' : IDL.Text,
    'createdAt' : IDL.Int,
    'authorAvatarBlobKey' : IDL.Text,
    'author' : IDL.Principal,
    'caption' : IDL.Text,
    'commentCount' : IDL.Nat,
    'likedByMe' : IDL.Bool,
  });
  const Highlight = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'owner' : IDL.Principal,
    'createdAt' : IDL.Int,
    'coverBlobKey' : IDL.Text,
    'storyIds' : IDL.Vec(IDL.Nat),
  });
  const NotificationType = IDL.Variant({
    'like' : IDL.Null,
    'comment' : IDL.Null,
    'mention' : IDL.Null,
    'follow' : IDL.Null,
  });
  const Notification = IDL.Record({
    'id' : IDL.Nat,
    'to' : IDL.Principal,
    'notificationType' : NotificationType,
    'from' : IDL.Principal,
    'read' : IDL.Bool,
    'text' : IDL.Opt(IDL.Text),
    'timestamp' : IDL.Int,
    'postId' : IDL.Opt(IDL.Nat),
  });
  const ReelView = IDL.Record({
    'id' : IDL.Nat,
    'audioLabel' : IDL.Text,
    'authorUsername' : IDL.Text,
    'likeCount' : IDL.Nat,
    'createdAt' : IDL.Int,
    'authorAvatarBlobKey' : IDL.Text,
    'videoBlobKey' : IDL.Text,
    'author' : IDL.Principal,
    'caption' : IDL.Text,
    'likedByMe' : IDL.Bool,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addComment' : IDL.Func([IDL.Nat, IDL.Text], [IDL.Nat], []),
    'addStoryToHighlight' : IDL.Func([IDL.Nat, IDL.Nat], [IDL.Bool], []),
    'answerQuestion' : IDL.Func([IDL.Nat, IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createHighlight' : IDL.Func([IDL.Text, IDL.Text], [IDL.Nat], []),
    'createPost' : IDL.Func([IDL.Text, IDL.Text], [IDL.Nat], []),
    'createReel' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [IDL.Nat], []),
    'createStory' : IDL.Func([IDL.Text, IDL.Text], [IDL.Nat], []),
    'deleteComment' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'deleteHighlight' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'deleteNotification' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'deletePost' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'deleteReel' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'followUser' : IDL.Func([IDL.Principal], [], []),
    'getActiveStories' : IDL.Func([], [IDL.Vec(StoryView)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(Profile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getComments' : IDL.Func([IDL.Nat], [IDL.Vec(Comment)], ['query']),
    'getConversations' : IDL.Func(
        [],
        [IDL.Vec(ConversationPreview)],
        ['query'],
      ),
    'getFeed' : IDL.Func([IDL.Nat], [IDL.Vec(PostView)], ['query']),
    'getFollowers' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(IDL.Principal)],
        ['query'],
      ),
    'getFollowing' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(IDL.Principal)],
        ['query'],
      ),
    'getHighlights' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(Highlight)],
        ['query'],
      ),
    'getMessagesWithUser' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(Message)],
        ['query'],
      ),
    'getMyHighlights' : IDL.Func([], [IDL.Vec(Highlight)], ['query']),
    'getMyProfile' : IDL.Func([], [IDL.Opt(Profile)], ['query']),
    'getNotifications' : IDL.Func([], [IDL.Vec(Notification)], ['query']),
    'getPost' : IDL.Func([IDL.Nat], [IDL.Opt(PostView)], ['query']),
    'getProfile' : IDL.Func([IDL.Principal], [IDL.Opt(Profile)], ['query']),
    'getReel' : IDL.Func([IDL.Nat], [IDL.Opt(ReelView)], ['query']),
    'getStoryViewers' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(IDL.Principal)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func([IDL.Principal], [IDL.Opt(Profile)], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isFollowing' : IDL.Func([IDL.Principal], [IDL.Bool], ['query']),
    'isLiked' : IDL.Func([IDL.Nat], [IDL.Bool], ['query']),
    'isReelLiked' : IDL.Func([IDL.Nat], [IDL.Bool], ['query']),
    'listPosts' : IDL.Func([], [IDL.Vec(PostView)], ['query']),
    'listProfiles' : IDL.Func([], [IDL.Vec(Profile)], ['query']),
    'listReels' : IDL.Func([], [IDL.Vec(ReelView)], ['query']),
    'markAllNotificationsRead' : IDL.Func([], [], []),
    'markNotificationRead' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'reactToStory' : IDL.Func([IDL.Nat, IDL.Text], [], []),
    'removeStoryFromHighlight' : IDL.Func([IDL.Nat, IDL.Nat], [IDL.Bool], []),
    'saveCallerUserProfile' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'sendMessage' : IDL.Func([IDL.Principal, IDL.Text], [IDL.Nat], []),
    'toggleLike' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'toggleReelLike' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'unfollowUser' : IDL.Func([IDL.Principal], [], []),
    'upsertProfile' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'viewStory' : IDL.Func([IDL.Nat], [], []),
    'votePoll' : IDL.Func([IDL.Nat, IDL.Text], [], []),
  });
};

export const init = ({ IDL }) => { return []; };